spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    check-template: true
    check-template-location: true
    enabled: true
    suffix: .html
  mvc:
    favicon:
      enabled: false

datasource:
  databaseDriverName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/spring_boot?verifyServerCertificate=false&useSSL=false
  username: root
  password: test
  maxPool: 50
  maxIdle: 10

resttemplate:
  connectTimeout: 30000
  socketTimeout: 15000
  maxPerRoute: 25
  maxTotalConnection: 100

server:
  port: 8110

pool:
  async-size: 50

session:
  timeout: 300